//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace catanafinals.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientLoan
    {
        public Nullable<int> ClientID { get; set; }
        public int LoanId { get; set; }
        public Nullable<decimal> LoanAmount { get; set; }
        public Nullable<int> Interest { get; set; }
        public string Term { get; set; }
        public Nullable<int> NumberOfPayment { get; set; }
        public Nullable<decimal> Deduction { get; set; }
        public Nullable<decimal> InterestedAmount { get; set; }
        public Nullable<decimal> ReceivableAmount { get; set; }
        public Nullable<decimal> TotalPayable { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string LoanStatus { get; set; }
    }
}
