//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace catanafinals.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int SchedID { get; set; }
        public Nullable<int> LoanID { get; set; }
        public Nullable<System.DateTime> PaymentSchedule { get; set; }
        public Nullable<decimal> Collectibles { get; set; }
        public string LoanStatus { get; set; }
    }
}
