//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace catanafinals.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transact
    {
        public int TransactionID { get; set; }
        public int LoanID { get; set; }
        public string PaymentType { get; set; }
        public decimal PaymentAmount { get; set; }
        public System.DateTime TransactionDate { get; set; }
    }
}
